### PR TITLE
Verbosity improvements

### PR DESCRIPTION
**Pull request by RobinD42**
Switch most mpb_verbosity checks to be >=1, and change the linmin messages to >=2

See https://github.com/NanoComp/meep/issues/1362 and https://github.com/NanoComp/meep/pull/1388

### CODE REVIEW

**Comment by thchr** [comment]
This seems to have the same problem that I brought up in https://github.com/NanoComp/mpb/pull/119#issuecomment-696341341 and fixed in https://github.com/NanoComp/mpb/pull/123?

Specifically, if the default verbosity level for MPB is 2, then this prints the linmin messages by default - which is a lot of extra stuff. That seems to be the current situation, cf. [Travis reports for this PR](https://travis-ci.org/github/NanoComp/mpb/jobs/733417886#L3744).

I'm guessing this works well with Meep, if it's reducing the verbosity level by 1 when calling out to MPB; but it's not too nice for working with MPB on its own.

**Comment by thchr** [comment]
@RobinD42: another consequence of this issue is that e.g. the Meep logs now exceed the allowable length on Travis due to repeated prints of "linmin: converged after ...", see e.g. https://travis-ci.org/github/NanoComp/meep/jobs/741695728#L79272

Wouldn't it better to roll back these changes to linmin printing?

**Comment by stevengj** [comment]
> Wouldn't it better to roll back these changes to linmin printing?

Yes, we can do that; it may have been an inadvertent change.  Can you make a PR?

**Comment by thchr** [comment]
Sure (I probably won't get around to it until the second half of next week though)!

**Comment by stevengj** [comment]
@thchr, we changed the MPB default verbosity to 1, which should fix this.  (It was already 1 in the Python interface.)

**Pull request merged**
